package network

import (
	"fmt"
	"strings"
)

// BondConfig holds the desired configuration for a bond.
type BondConfig struct {
	Name      string          `json:"name"`
	Mode      string          `json:"mode"`       // "802.3ad", "balance-rr", "active-backup", etc.
	Members   []string        `json:"members"`    // interface names
	IPv4Addrs []string        `json:"ipv4_addrs"`
	IPv6Addrs []string        `json:"ipv6_addrs"`
	Gateway4  string          `json:"gateway4"`
	Gateway6  string          `json:"gateway6"`
	DHCP4     bool            `json:"dhcp4"`
	DHCP6     bool            `json:"dhcp6"`
	SLAAC     bool            `json:"slaac"`
	MTU       int             `json:"mtu"`
	DNS       []string        `json:"dns"`
}

var validBondModes = map[string]bool{
	"802.3ad":       true,
	"balance-rr":    true,
	"active-backup": true,
	"balance-xor":   true,
	"balance-tlb":   true,
	"balance-alb":   true,
}

// ValidateBondMode checks if a bond mode is supported.
func ValidateBondMode(mode string) error {
	if !validBondModes[mode] {
		return fmt.Errorf("invalid bond mode: %s (must be 802.3ad, balance-rr, active-backup, balance-xor, balance-tlb, or balance-alb)", mode)
	}
	return nil
}

// ValidateBondName checks that a bond name is safe (e.g. "bond0").
func ValidateBondName(name string) error {
	if !strings.HasPrefix(name, "bond") {
		return fmt.Errorf("bond name must start with 'bond': %s", name)
	}
	return ValidateInterfaceName(name)
}

// GenerateBondNetdev generates a systemd-networkd .netdev file for a bond.
func GenerateBondNetdev(bond BondConfig) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by tierd. Do not edit.\n")
	fmt.Fprintf(&b, "[NetDev]\nName=%s\nKind=bond\n\n", bond.Name)

	b.WriteString("[Bond]\n")
	fmt.Fprintf(&b, "Mode=%s\n", bond.Mode)

	if bond.Mode == "802.3ad" {
		b.WriteString("TransmitHashPolicy=layer3+4\n")
		b.WriteString("MIIMonitorSec=100ms\n")
		b.WriteString("LACPTransmitRate=fast\n")
	} else {
		b.WriteString("MIIMonitorSec=100ms\n")
	}

	return b.String()
}

// GenerateBondMemberNetwork generates a .network file for a bond member interface.
func GenerateBondMemberNetwork(memberName, bondName string) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by tierd. Do not edit.\n")
	fmt.Fprintf(&b, "[Match]\nName=%s\n\n", memberName)
	fmt.Fprintf(&b, "[Network]\nBond=%s\n", bondName)

	return b.String()
}

// GenerateBondNetwork generates a .network file for the bond interface itself.
func GenerateBondNetwork(bond BondConfig) string {
	// Reuse the interface config generator.
	cfg := InterfaceConfig{
		Name:      bond.Name,
		IPv4Addrs: bond.IPv4Addrs,
		IPv6Addrs: bond.IPv6Addrs,
		Gateway4:  bond.Gateway4,
		Gateway6:  bond.Gateway6,
		DHCP4:     bond.DHCP4,
		DHCP6:     bond.DHCP6,
		SLAAC:     bond.SLAAC,
		MTU:       bond.MTU,
		DNS:       bond.DNS,
	}
	return GenerateNetworkFile(cfg)
}
