package network

import (
	"fmt"
	"strings"
)

// VLANConfig holds the desired configuration for a VLAN.
type VLANConfig struct {
	Parent    string   `json:"parent"`     // parent interface or bond name
	ID        int      `json:"id"`         // VLAN ID 1-4094
	Name      string   `json:"name"`       // e.g. "bond0.100"
	IPv4Addrs []string `json:"ipv4_addrs"`
	IPv6Addrs []string `json:"ipv6_addrs"`
	Gateway4  string   `json:"gateway4"`
	Gateway6  string   `json:"gateway6"`
	DHCP4     bool     `json:"dhcp4"`
	DHCP6     bool     `json:"dhcp6"`
	SLAAC     bool     `json:"slaac"`
	MTU       int      `json:"mtu"`
	DNS       []string `json:"dns"`
}

// ValidateVLANID checks that a VLAN ID is in the valid range.
func ValidateVLANID(id int) error {
	if id < 1 || id > 4094 {
		return fmt.Errorf("invalid VLAN ID %d (must be 1-4094)", id)
	}
	return nil
}

// VLANName generates the interface name for a VLAN.
func VLANName(parent string, id int) string {
	return fmt.Sprintf("%s.%d", parent, id)
}

// GenerateVLANNetdev generates a systemd-networkd .netdev file for a VLAN.
func GenerateVLANNetdev(vlan VLANConfig) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by tierd. Do not edit.\n")
	fmt.Fprintf(&b, "[NetDev]\nName=%s\nKind=vlan\n\n", vlan.Name)
	fmt.Fprintf(&b, "[VLAN]\nId=%d\n", vlan.ID)

	return b.String()
}

// GenerateVLANNetwork generates a .network file for a VLAN interface.
func GenerateVLANNetwork(vlan VLANConfig) string {
	cfg := InterfaceConfig{
		Name:      vlan.Name,
		IPv4Addrs: vlan.IPv4Addrs,
		IPv6Addrs: vlan.IPv6Addrs,
		Gateway4:  vlan.Gateway4,
		Gateway6:  vlan.Gateway6,
		DHCP4:     vlan.DHCP4,
		DHCP6:     vlan.DHCP6,
		SLAAC:     vlan.SLAAC,
		MTU:       vlan.MTU,
		DNS:       vlan.DNS,
	}
	return GenerateNetworkFile(cfg)
}

// AddVLANToParentNetwork returns a VLAN= line to add to the parent's .network file.
func AddVLANToParentNetwork(vlanName string) string {
	return fmt.Sprintf("VLAN=%s\n", vlanName)
}
