// Package firewall manages nftables rules for sharing protocol ports.
//
// tierd generates a complete nftables ruleset on every change. The base
// ruleset allows SSH (22) and HTTPS (443). Sharing protocol ports are
// added/removed dynamically as protocols are enabled/disabled.
package firewall

import (
	"fmt"
	"os"
	"os/exec"
	"strings"

	"github.com/JBailes/SmoothNAS/tierd/internal/nfs"
)

// Protocol represents a sharing protocol and its ports.
type Protocol struct {
	Name    string `json:"name"`
	Enabled bool   `json:"enabled"`
	Ports   []Port `json:"ports"`
}

// Port represents a firewall port rule.
type Port struct {
	Number   int    `json:"number"`
	Protocol string `json:"protocol"` // "tcp" or "udp"
	Comment  string `json:"comment"`
}

// ProtocolPorts defines the ports needed by each sharing protocol.
var ProtocolPorts = map[string][]Port{
	"smb": {
		{Number: 445, Protocol: "tcp", Comment: "SMB"},
	},
	"nfs": {
		{Number: 2049, Protocol: "tcp", Comment: "NFS"},
		{Number: 111, Protocol: "tcp", Comment: "rpcbind (NFSv3)"},
		{Number: 111, Protocol: "udp", Comment: "rpcbind (NFSv3)"},
		{Number: nfs.MountdPort, Protocol: "tcp", Comment: "mountd (NFSv3)"},
		{Number: nfs.MountdPort, Protocol: "udp", Comment: "mountd (NFSv3)"},
		{Number: nfs.StatdPort, Protocol: "tcp", Comment: "statd (NFSv3)"},
		{Number: nfs.StatdPort, Protocol: "udp", Comment: "statd (NFSv3)"},
		{Number: nfs.LockdPort, Protocol: "tcp", Comment: "lockd (NFSv3)"},
		{Number: nfs.LockdPort, Protocol: "udp", Comment: "lockd (NFSv3)"},
	},
	"iscsi": {
		{Number: 3260, Protocol: "tcp", Comment: "iSCSI"},
	},
}

// ValidateProtocol checks if a protocol name is recognized.
func ValidateProtocol(name string) error {
	if _, ok := ProtocolPorts[name]; !ok {
		return fmt.Errorf("unknown protocol: %s (must be smb, nfs, or iscsi)", name)
	}
	return nil
}

// GenerateRuleset produces the full nftables ruleset.
func GenerateRuleset(enabledProtocols map[string]bool) string {
	var b strings.Builder

	b.WriteString("#!/usr/sbin/nft -f\n")
	b.WriteString("# Auto-generated by tierd. Do not edit.\n\n")
	b.WriteString("flush ruleset\n\n")

	b.WriteString("table inet filter {\n")

	// Input chain.
	b.WriteString("    chain input {\n")
	b.WriteString("        type filter hook input priority 0; policy drop;\n\n")
	b.WriteString("        # Allow established/related.\n")
	b.WriteString("        ct state established,related accept\n\n")
	b.WriteString("        # Allow loopback.\n")
	b.WriteString("        iif lo accept\n\n")
	b.WriteString("        # Allow ICMP/ICMPv6.\n")
	b.WriteString("        meta l4proto icmp accept\n")
	b.WriteString("        meta l4proto icmpv6 accept\n\n")
	b.WriteString("        # Base services (always open).\n")
	b.WriteString("        tcp dport 22 accept comment \"SSH\"\n")
	b.WriteString("        tcp dport 443 accept comment \"HTTPS\"\n")
	b.WriteString("        tcp dport 8420 accept comment \"tierd API (localhost only via nginx)\"\n\n")

	// Sharing protocol ports.
	for proto, ports := range ProtocolPorts {
		if !enabledProtocols[proto] {
			continue
		}
		fmt.Fprintf(&b, "        # %s\n", strings.ToUpper(proto))
		for _, port := range ports {
			fmt.Fprintf(&b, "        %s dport %d accept comment \"%s\"\n",
				port.Protocol, port.Number, port.Comment)
		}
		b.WriteString("\n")
	}

	b.WriteString("    }\n\n")

	// Forward chain (default drop).
	b.WriteString("    chain forward {\n")
	b.WriteString("        type filter hook forward priority 0; policy drop;\n")
	b.WriteString("    }\n\n")

	// Output chain (allow all).
	b.WriteString("    chain output {\n")
	b.WriteString("        type filter hook output priority 0; policy accept;\n")
	b.WriteString("    }\n")

	b.WriteString("}\n")

	return b.String()
}

// Apply writes the nftables ruleset and loads it.
func Apply(enabledProtocols map[string]bool) error {
	ruleset := GenerateRuleset(enabledProtocols)

	confPath := "/etc/nftables.conf"
	if err := os.WriteFile(confPath, []byte(ruleset), 0644); err != nil {
		return fmt.Errorf("write nftables.conf: %w", err)
	}

	cmd := exec.Command("nft", "-f", confPath)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("nft apply: %s: %w", strings.TrimSpace(string(out)), err)
	}

	return nil
}

// GetEnabledProtocols checks which sharing protocols have their services active.
func GetEnabledProtocols() map[string]bool {
	enabled := make(map[string]bool)
	// Check each protocol's primary service.
	if exec.Command("systemctl", "is-active", "--quiet", "smbd").Run() == nil {
		enabled["smb"] = true
	}
	if exec.Command("systemctl", "is-active", "--quiet", "nfs-kernel-server").Run() == nil {
		enabled["nfs"] = true
	}
	if exec.Command("systemctl", "is-active", "--quiet", "rtslib-fb-targetctl").Run() == nil {
		enabled["iscsi"] = true
	}
	return enabled
}
