// Package smb manages Samba shares via smb.conf generation and smbcontrol.
//
// tierd owns /etc/samba/smb.conf. It generates the full config from its
// internal state on every change. Manual edits are overwritten.
package smb

import (
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"strings"
)

// Share represents an SMB share definition.
type Share struct {
	Name       string   `json:"name"`
	Path       string   `json:"path"`
	ReadOnly   bool     `json:"read_only"`
	GuestOK    bool     `json:"guest_ok"`
	AllowUsers []string `json:"allow_users,omitempty"` // empty = all users
	Comment    string   `json:"comment"`
}

var shareNameRegex = regexp.MustCompile(`^[a-zA-Z][a-zA-Z0-9_-]{0,63}$`)

// ValidateShareName checks that a share name is safe for smb.conf.
func ValidateShareName(name string) error {
	if !shareNameRegex.MatchString(name) {
		return fmt.Errorf("invalid share name: %s", name)
	}
	reserved := map[string]bool{"global": true, "homes": true, "printers": true}
	if reserved[strings.ToLower(name)] {
		return fmt.Errorf("reserved share name: %s", name)
	}
	return nil
}

// ValidateSharePath checks that the path is under /mnt/.
func ValidateSharePath(path string) error {
	if !strings.HasPrefix(path, "/mnt/") && !strings.HasPrefix(path, "/") {
		return fmt.Errorf("share path must be absolute: %s", path)
	}
	for _, c := range path {
		if c == ';' || c == '$' || c == '`' || c == '\'' || c == '"' {
			return fmt.Errorf("share path contains invalid character: %c", c)
		}
	}
	return nil
}

// GenerateConfig produces the full smb.conf content from a list of shares.
func GenerateConfig(shares []Share, hostname string) string {
	var b strings.Builder

	// Global section.
	b.WriteString("# Auto-generated by tierd. Do not edit.\n")
	b.WriteString("[global]\n")
	b.WriteString("   workgroup = WORKGROUP\n")
	fmt.Fprintf(&b, "   server string = %s\n", hostname)
	b.WriteString("   security = user\n")
	b.WriteString("   map to guest = never\n")
	b.WriteString("   log file = /var/log/samba/log.%m\n")
	b.WriteString("   max log size = 1000\n")
	b.WriteString("   server role = standalone server\n")
	b.WriteString("   obey pam restrictions = yes\n")
	b.WriteString("   unix password sync = yes\n")
	b.WriteString("   pam password change = yes\n")
	// Throughput tuning: 8 MB socket buffers, zero-copy sendfile, async I/O.
	b.WriteString("   socket options = TCP_NODELAY IPTOS_THROUGHPUT SO_RCVBUF=8388608 SO_SNDBUF=8388608\n")
	b.WriteString("   use sendfile = yes\n")
	b.WriteString("   aio read size = 1\n")
	b.WriteString("   aio write size = 1\n")
	b.WriteString("   read raw = yes\n")
	b.WriteString("   write raw = yes\n")
	b.WriteString("   large readwrite = yes\n")
	b.WriteString("\n")

	// Share sections.
	for _, share := range shares {
		fmt.Fprintf(&b, "[%s]\n", share.Name)
		if share.Comment != "" {
			fmt.Fprintf(&b, "   comment = %s\n", share.Comment)
		}
		fmt.Fprintf(&b, "   path = %s\n", share.Path)
		if share.ReadOnly {
			b.WriteString("   read only = yes\n")
		} else {
			b.WriteString("   read only = no\n")
		}
		if share.GuestOK {
			b.WriteString("   guest ok = yes\n")
		} else {
			b.WriteString("   guest ok = no\n")
		}
		if len(share.AllowUsers) > 0 {
			fmt.Fprintf(&b, "   valid users = %s\n", strings.Join(share.AllowUsers, " "))
		}
		b.WriteString("   create mask = 0664\n")
		b.WriteString("   directory mask = 0775\n")
		b.WriteString("\n")
	}

	return b.String()
}

// WriteConfig writes the generated smb.conf and reloads Samba.
func WriteConfig(shares []Share, hostname string) error {
	config := GenerateConfig(shares, hostname)

	if err := os.MkdirAll("/etc/samba", 0755); err != nil {
		return fmt.Errorf("create samba dir: %w", err)
	}

	if err := os.WriteFile("/etc/samba/smb.conf", []byte(config), 0644); err != nil {
		return fmt.Errorf("write smb.conf: %w", err)
	}

	return Reload()
}

// Reload tells Samba to re-read its configuration.
func Reload() error {
	cmd := exec.Command("smbcontrol", "all", "reload-config")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("smbcontrol reload: %s: %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

// SyncUser syncs a system user's password to Samba's password database.
// Called when a user is created or changes their password.
func SyncUser(username, password string) error {
	cmd := exec.Command("smbpasswd", "-a", "-s", username)
	cmd.Stdin = strings.NewReader(password + "\n" + password + "\n")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("smbpasswd: %s: %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

// RemoveUser removes a user from Samba's password database.
func RemoveUser(username string) error {
	cmd := exec.Command("smbpasswd", "-x", username)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("smbpasswd remove: %s: %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

// EnableService starts and enables smbd and nmbd.
func EnableService() error {
	for _, svc := range []string{"smbd", "nmbd"} {
		if err := exec.Command("systemctl", "enable", "--now", svc).Run(); err != nil {
			return fmt.Errorf("enable %s: %w", svc, err)
		}
	}
	return nil
}

// DisableService stops and disables smbd and nmbd.
func DisableService() error {
	for _, svc := range []string{"smbd", "nmbd"} {
		if err := exec.Command("systemctl", "disable", "--now", svc).Run(); err != nil {
			return fmt.Errorf("disable %s: %w", svc, err)
		}
	}
	return nil
}

// IsEnabled checks if smbd is active.
func IsEnabled() bool {
	return exec.Command("systemctl", "is-active", "--quiet", "smbd").Run() == nil
}
