// Package nfs manages NFS exports via /etc/exports generation and exportfs.
//
// tierd owns /etc/exports. It generates the full file from its internal
// state on every change. Manual edits are overwritten.
package nfs

import (
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	ServerThreads = 32
	MaxBlockSize  = 2 * 1024 * 1024

	MountdPort = 20048
	StatdPort  = 32765
	// StatdOutgoingPort pins rpc.statd's source port for NSM callbacks.
	StatdOutgoingPort = 32766
	LockdPort         = 32767

	ClientSunRPCSlots = 128

	// DefaultClientMountOptions are used when SmoothNAS is the NFS client
	// for backup and benchmark operations. Linux currently negotiates
	// rsize/wsize down to the server's max payload, so these are safe on
	// servers that still cap at 1 MiB.
	DefaultClientMountOptions = "vers=4.2,rsize=2097152,wsize=2097152,lookupcache=all,actimeo=60,timeo=50,retrans=3"
)

var (
	serverTuningPath     = "/etc/nfs.conf.d/smoothnas.conf"
	lockdSysctlPath      = "/etc/sysctl.d/99-smoothnas-nfs.conf"
	lockdModprobePath    = "/etc/modprobe.d/smoothnas-lockd.conf"
	nfsdDropInPath       = "/etc/systemd/system/nfs-server.service.d/10-smoothnas-tuning.conf"
	nfsKernelDropInPath  = "/etc/systemd/system/nfs-kernel-server.service.d/10-smoothnas-tuning.conf"
	procNFSMaxBlockPath  = "/proc/fs/nfsd/max_block_size"
	procSunRPCSlotTable  = "/sys/module/sunrpc/parameters/tcp_slot_table_entries"
	procLockdTCPPortPath = "/proc/sys/fs/nfs/nlm_tcpport"
	procLockdUDPPortPath = "/proc/sys/fs/nfs/nlm_udpport"
	procNfsdThreadsPath  = "/proc/fs/nfsd/threads"
)

// Export represents an NFS export definition.
type Export struct {
	Path       string   `json:"path"`
	Networks   []string `json:"networks"`    // e.g. ["192.168.1.0/24", "10.0.0.0/8"]
	Sync       bool     `json:"sync"`        // sync vs async
	RootSquash bool     `json:"root_squash"` // root_squash vs no_root_squash
	NFSv3      bool     `json:"nfsv3"`       // allow NFSv3 (requires rpcbind)
	ReadOnly   bool     `json:"read_only"`
	// Fsid, if non-empty, is rendered as `fsid=<value>` in /etc/exports.
	// For smoothfs-backed exports it MUST equal SmoothfsFsid(poolUUID)
	// so the kernel-emitted handle prefix matches what nfsd routes by.
	// Empty leaves the option off (nfsd auto-derives from sb identity).
	Fsid string `json:"fsid,omitempty"`
}

var exportPathRegex = regexp.MustCompile(`^/[a-zA-Z0-9/_.-]+$`)

// ValidateExportPath checks that the path is a safe absolute path.
func ValidateExportPath(path string) error {
	if !exportPathRegex.MatchString(path) {
		return fmt.Errorf("invalid export path: %s", path)
	}
	return nil
}

// ValidateNetwork checks that a network string is a valid CIDR, IP, or hostname.
func ValidateNetwork(network string) error {
	// Accept CIDR notation.
	if _, _, err := net.ParseCIDR(network); err == nil {
		return nil
	}
	// Accept single IP.
	if ip := net.ParseIP(network); ip != nil {
		return nil
	}
	// Accept * (all hosts).
	if network == "*" {
		return nil
	}
	// Accept simple hostnames.
	hostnameRegex := regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9.-]+$`)
	if hostnameRegex.MatchString(network) {
		return nil
	}
	return fmt.Errorf("invalid network: %s", network)
}

// GenerateExports produces the /etc/exports content from a list of exports.
func GenerateExports(exports []Export) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by tierd. Do not edit.\n")

	for _, exp := range exports {
		for _, network := range exp.Networks {
			options := buildOptions(exp)
			fmt.Fprintf(&b, "%s %s(%s)\n", exp.Path, network, options)
		}
	}

	return b.String()
}

func buildOptions(exp Export) string {
	var opts []string

	if exp.ReadOnly {
		opts = append(opts, "ro")
	} else {
		opts = append(opts, "rw")
	}

	if exp.Sync {
		opts = append(opts, "sync")
	} else {
		opts = append(opts, "async")
	}

	if exp.RootSquash {
		opts = append(opts, "root_squash")
	} else {
		opts = append(opts, "no_root_squash")
	}

	opts = append(opts, "no_subtree_check")

	if exp.Fsid != "" {
		opts = append(opts, "fsid="+exp.Fsid)
	}

	return strings.Join(opts, ",")
}

// WriteExports writes /etc/exports and reloads.
func WriteExports(exports []Export) error {
	content := GenerateExports(exports)

	if err := os.WriteFile("/etc/exports", []byte(content), 0644); err != nil {
		return fmt.Errorf("write exports: %w", err)
	}

	return ReloadExports()
}

func ServerTuningConfig() string {
	return fmt.Sprintf(`# Auto-generated by tierd. Do not edit.
[nfsd]
threads = %d
vers3 = y
vers4 = y
vers4.1 = y
vers4.2 = y

[mountd]
port = %d
threads = 16

[statd]
port = %d
outgoing-port = %d

[lockd]
port = %d
udp-port = %d
`, ServerThreads, MountdPort, StatdPort, StatdOutgoingPort, LockdPort, LockdPort)
}

func NfsdSystemdDropInConfig() string {
	return fmt.Sprintf(`[Service]
ExecStartPre=/bin/sh -c 'if [ -w /proc/fs/nfsd/max_block_size ]; then echo %d > /proc/fs/nfsd/max_block_size; fi'
`, MaxBlockSize)
}

func LockdSysctlConfig() string {
	return fmt.Sprintf(`# Auto-generated by tierd. Do not edit.
fs.nfs.nlm_tcpport = %d
fs.nfs.nlm_udpport = %d
`, LockdPort, LockdPort)
}

func LockdModprobeConfig() string {
	return fmt.Sprintf(`# Auto-generated by tierd. Do not edit.
options lockd nlm_tcpport=%d nlm_udpport=%d
`, LockdPort, LockdPort)
}

func ApplyServerTuning() error {
	if err := writeManagedFile(serverTuningPath, ServerTuningConfig()); err != nil {
		return fmt.Errorf("write nfs server tuning: %w", err)
	}
	if err := writeManagedFile(lockdSysctlPath, LockdSysctlConfig()); err != nil {
		return fmt.Errorf("write lockd sysctl tuning: %w", err)
	}
	if err := writeManagedFile(lockdModprobePath, LockdModprobeConfig()); err != nil {
		return fmt.Errorf("write lockd module tuning: %w", err)
	}
	if err := writeManagedFile(nfsdDropInPath, NfsdSystemdDropInConfig()); err != nil {
		return fmt.Errorf("write nfsd systemd tuning: %w", err)
	}
	if err := writeManagedFile(nfsKernelDropInPath, NfsdSystemdDropInConfig()); err != nil {
		return fmt.Errorf("write nfs-kernel-server systemd tuning: %w", err)
	}
	if err := applyRuntimeLockdTuning(); err != nil {
		return err
	}
	if err := applyRuntimeNfsdMaxBlockSize(); err != nil {
		return err
	}
	if err := applyRuntimeSunRPCSlots(); err != nil {
		return err
	}
	return nil
}

func writeManagedFile(path string, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func applyRuntimeLockdTuning() error {
	for _, path := range []string{
		procLockdTCPPortPath,
		procLockdUDPPortPath,
	} {
		if _, err := os.Stat(path); err != nil {
			if os.IsNotExist(err) {
				return nil
			}
			return fmt.Errorf("stat lockd runtime tuning: %w", err)
		}
	}
	out, err := exec.Command(
		"sysctl", "-q", "-w",
		fmt.Sprintf("fs.nfs.nlm_tcpport=%d", LockdPort),
		fmt.Sprintf("fs.nfs.nlm_udpport=%d", LockdPort),
	).CombinedOutput()
	if err != nil {
		return fmt.Errorf("apply lockd runtime tuning: %s: %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

func applyRuntimeNfsdThreads() error {
	path := procNfsdThreadsPath
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat nfsd threads: %w", err)
	}
	if err := os.WriteFile(path, []byte(fmt.Sprintf("%d\n", ServerThreads)), 0o644); err != nil {
		return fmt.Errorf("apply nfsd thread tuning: %w", err)
	}
	return nil
}

func applyRuntimeNfsdMaxBlockSize() error {
	path := procNFSMaxBlockPath
	if _, err := os.Stat(path); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat nfsd max block size: %w", err)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("read nfsd max block size: %w", err)
	}
	current, err := parseInt(strings.TrimSpace(string(raw)))
	if err != nil {
		return fmt.Errorf("parse nfsd max block size: %w", err)
	}
	if current >= MaxBlockSize {
		return nil
	}
	if err := os.WriteFile(path, []byte(fmt.Sprintf("%d\n", MaxBlockSize)), 0o644); err != nil {
		return fmt.Errorf("apply nfsd max block size tuning: %w", err)
	}
	return nil
}

func applyRuntimeSunRPCSlots() error {
	if _, err := os.Stat(procSunRPCSlotTable); err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("stat sunrpc slot table entries: %w", err)
	}
	if err := os.WriteFile(procSunRPCSlotTable, []byte(fmt.Sprintf("%d\n", ClientSunRPCSlots)), 0o644); err != nil {
		return fmt.Errorf("apply sunrpc slot table tuning: %w", err)
	}
	return nil
}

func NFSMaxBlockSize() (string, bool) {
	return readTrimmed(procNFSMaxBlockPath)
}

func SunRPCSlotTableEntries() (string, bool) {
	return readTrimmed(procSunRPCSlotTable)
}

func readTrimmed(path string) (string, bool) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", false
	}
	return strings.TrimSpace(string(raw)), true
}

func TuningFiles() []string {
	return []string{
		serverTuningPath,
		lockdSysctlPath,
		lockdModprobePath,
		filepath.Clean(nfsdDropInPath),
		filepath.Clean(nfsKernelDropInPath),
	}
}

func parseInt(s string) (int64, error) {
	var n int64
	if _, err := fmt.Sscanf(s, "%d", &n); err != nil {
		return 0, err
	}
	return n, nil
}

// ReloadExports runs exportfs -ra to apply changes.
func ReloadExports() error {
	cmd := exec.Command("exportfs", "-ra")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("exportfs: %s: %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

// EnableService starts and enables nfs-kernel-server and rpcbind.
func EnableService(enableV3 bool) error {
	if err := ApplyServerTuning(); err != nil {
		return err
	}
	if err := systemctl("daemon-reload"); err != nil {
		return err
	}
	if enableV3 {
		if err := systemctl("enable", "--now", "rpcbind"); err != nil {
			return err
		}
		if err := systemctl("restart", "rpc-statd"); err != nil {
			return err
		}
	}
	if err := systemctl("enable", "nfs-kernel-server"); err != nil {
		return err
	}
	if err := systemctl("restart", "nfs-kernel-server"); err != nil {
		return err
	}
	if err := applyRuntimeNfsdThreads(); err != nil {
		return err
	}
	return nil
}

func systemctl(args ...string) error {
	out, err := exec.Command("systemctl", args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("systemctl %s: %s: %w", strings.Join(args, " "), strings.TrimSpace(string(out)), err)
	}
	return nil
}

// DisableService stops and disables NFS services.
func DisableService() error {
	exec.Command("systemctl", "disable", "--now", "nfs-kernel-server").Run()
	exec.Command("systemctl", "stop", "rpc-statd").Run()
	exec.Command("systemctl", "disable", "--now", "rpcbind").Run()
	return nil
}

// IsEnabled checks if nfs-kernel-server is active.
func IsEnabled() bool {
	return exec.Command("systemctl", "is-active", "--quiet", "nfs-kernel-server").Run() == nil
}

// BuildOptions is exported for testing.
func BuildOptions(exp Export) string {
	return buildOptions(exp)
}
