// Package nfs manages NFS exports via /etc/exports generation and exportfs.
//
// tierd owns /etc/exports. It generates the full file from its internal
// state on every change. Manual edits are overwritten.
package nfs

import (
	"fmt"
	"net"
	"os"
	"os/exec"
	"regexp"
	"strings"
)

// Export represents an NFS export definition.
type Export struct {
	Path       string   `json:"path"`
	Networks   []string `json:"networks"`     // e.g. ["192.168.1.0/24", "10.0.0.0/8"]
	Sync       bool     `json:"sync"`         // sync vs async
	RootSquash bool     `json:"root_squash"`  // root_squash vs no_root_squash
	NFSv3      bool     `json:"nfsv3"`        // allow NFSv3 (requires rpcbind)
	ReadOnly   bool     `json:"read_only"`
}

var exportPathRegex = regexp.MustCompile(`^/[a-zA-Z0-9/_.-]+$`)

// ValidateExportPath checks that the path is a safe absolute path.
func ValidateExportPath(path string) error {
	if !exportPathRegex.MatchString(path) {
		return fmt.Errorf("invalid export path: %s", path)
	}
	return nil
}

// ValidateNetwork checks that a network string is a valid CIDR, IP, or hostname.
func ValidateNetwork(network string) error {
	// Accept CIDR notation.
	if _, _, err := net.ParseCIDR(network); err == nil {
		return nil
	}
	// Accept single IP.
	if ip := net.ParseIP(network); ip != nil {
		return nil
	}
	// Accept * (all hosts).
	if network == "*" {
		return nil
	}
	// Accept simple hostnames.
	hostnameRegex := regexp.MustCompile(`^[a-zA-Z0-9][a-zA-Z0-9.-]+$`)
	if hostnameRegex.MatchString(network) {
		return nil
	}
	return fmt.Errorf("invalid network: %s", network)
}

// GenerateExports produces the /etc/exports content from a list of exports.
func GenerateExports(exports []Export) string {
	var b strings.Builder
	b.WriteString("# Auto-generated by tierd. Do not edit.\n")

	for _, exp := range exports {
		for _, network := range exp.Networks {
			options := buildOptions(exp)
			fmt.Fprintf(&b, "%s %s(%s)\n", exp.Path, network, options)
		}
	}

	return b.String()
}

func buildOptions(exp Export) string {
	var opts []string

	if exp.ReadOnly {
		opts = append(opts, "ro")
	} else {
		opts = append(opts, "rw")
	}

	if exp.Sync {
		opts = append(opts, "sync")
	} else {
		opts = append(opts, "async")
	}

	if exp.RootSquash {
		opts = append(opts, "root_squash")
	} else {
		opts = append(opts, "no_root_squash")
	}

	opts = append(opts, "no_subtree_check")

	return strings.Join(opts, ",")
}

// WriteExports writes /etc/exports and reloads.
func WriteExports(exports []Export) error {
	content := GenerateExports(exports)

	if err := os.WriteFile("/etc/exports", []byte(content), 0644); err != nil {
		return fmt.Errorf("write exports: %w", err)
	}

	return ReloadExports()
}

// ReloadExports runs exportfs -ra to apply changes.
func ReloadExports() error {
	cmd := exec.Command("exportfs", "-ra")
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("exportfs: %s: %w", strings.TrimSpace(string(out)), err)
	}
	return nil
}

// EnableService starts and enables nfs-kernel-server and rpcbind.
func EnableService(enableV3 bool) error {
	if enableV3 {
		if err := exec.Command("systemctl", "enable", "--now", "rpcbind").Run(); err != nil {
			return fmt.Errorf("enable rpcbind: %w", err)
		}
	}
	if err := exec.Command("systemctl", "enable", "--now", "nfs-kernel-server").Run(); err != nil {
		return fmt.Errorf("enable nfs-kernel-server: %w", err)
	}
	return nil
}

// DisableService stops and disables NFS services.
func DisableService() error {
	exec.Command("systemctl", "disable", "--now", "nfs-kernel-server").Run()
	exec.Command("systemctl", "disable", "--now", "rpcbind").Run()
	return nil
}

// IsEnabled checks if nfs-kernel-server is active.
func IsEnabled() bool {
	return exec.Command("systemctl", "is-active", "--quiet", "nfs-kernel-server").Run() == nil
}

// BuildOptions is exported for testing.
func BuildOptions(exp Export) string {
	return buildOptions(exp)
}
